name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    # Runs on pull requests to any branch

jobs:
  build-and-test:
    name: Swift ${{ matrix.swift-version }}, VIPS ${{ matrix.vips-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift-version: ["6.2.1"]
        vips-version: ["8.15.5", "8.16.1", "8.17.2"]
    container:
      image: ghcr.io/t089/swift-vips-builder:swift-${{ matrix.swift-version }}-vips-${{ matrix.vips-version }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: swift build --build-tests
    
    - name: Run tests
      run: swift test
    
    - name: Build release
      run: swift build -c release